apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcx-public-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcx-public-ui-app

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: arcx-public-ui-app
    spec:
      securityContext:
        runAsUser: 555
        runAsGroup: 555
        fsGroup: 555
      containers:
      - name: app
        image: $CI_REGISTRY_IMAGE/public-ui-app:$CI_COMMIT_REF_SLUG
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: arcx-public-ui-configmap
        env:
          - name: REDEPLOY_META
            value: $CI_JOB_ID-$CI_COMMIT_SHA

          - name: VUE_APP_API_AREA_OF_INTEREST
            value: "$VUE_APP_API_AREA_OF_INTEREST"
          - name: VUE_APP_API_AREA_OF_INTEREST_ITEMS
            value: "$VUE_APP_API_AREA_OF_INTEREST_ITEMS"
          - name: VUE_APP_API_AREA_OF_INTEREST_SUB_ITEMS
            value: "$VUE_APP_API_AREA_OF_INTEREST_SUB_ITEMS"
          - name: VUE_APP_API_STEPS_TO_HELP_PREPARE
            value: "$VUE_APP_API_STEPS_TO_HELP_PREPARE"
          - name: VUE_APP_API_STEPS_TO_HELP_PREPARE_ITEMS
            value: "$VUE_APP_API_STEPS_TO_HELP_PREPARE_ITEMS"      
          - name: VUE_APP_API_URL
            value: "$VUE_APP_API_URL"
          - name: VUE_APP_TITLE
            value: "$VUE_APP_TITLE"
        livenessProbe:
         tcpSocket:
            port: 8080
         initialDelaySeconds: 10
         periodSeconds: 15
        readinessProbe:
         tcpSocket:
            port: 8080
         initialDelaySeconds: 15
         periodSeconds: 10
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: glcr-auth
---

apiVersion: v1
kind: Service
metadata:
  name: arcx-public-ui-app-service
spec:
  ports:
  - port: 8080
  selector:
    app: arcx-public-ui-app
